
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Himanshu
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        halwarb = new javax.swing.JRadioButton();
        gajarrb = new javax.swing.JRadioButton();
        mulirb = new javax.swing.JRadioButton();
        benganrb = new javax.swing.JRadioButton();
        duarb = new javax.swing.JRadioButton();
        mrurb = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        BUYBTN = new javax.swing.JButton();
        CLEARBTN = new javax.swing.JButton();
        CANCELBTN = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        MONEYTF = new javax.swing.JTextField();
        CHNAGETF = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setText("VENDING MACHINE");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("SELECT ITEMS"));

        halwarb.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        halwarb.setText("HALWA");
        halwarb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                halwarbActionPerformed(evt);
            }
        });

        gajarrb.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        gajarrb.setText("GAJAR");
        gajarrb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gajarrbActionPerformed(evt);
            }
        });

        mulirb.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        mulirb.setText("MULI");
        mulirb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mulirbActionPerformed(evt);
            }
        });

        benganrb.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        benganrb.setText("BENGAN");
        benganrb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                benganrbActionPerformed(evt);
            }
        });

        duarb.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        duarb.setText("DUA");
        duarb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                duarbActionPerformed(evt);
            }
        });

        mrurb.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        mrurb.setText("MRU");
        mrurb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mrurbActionPerformed(evt);
            }
        });

        jLabel2.setText("100 RS");

        jLabel3.setText("1000 RS");

        jLabel4.setText("300 RS");

        jLabel5.setText("900 RS");

        jLabel6.setText("1000 RS");

        jLabel7.setText("1 RS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(halwarb)
                            .addComponent(benganrb)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jLabel2)))
                        .addGap(118, 118, 118)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(gajarrb)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jLabel3))
                            .addComponent(duarb)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addGap(16, 16, 16)))
                .addGap(89, 89, 89)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(mulirb)
                            .addComponent(mrurb))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(28, 28, 28))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(halwarb)
                    .addComponent(gajarrb)
                    .addComponent(mulirb))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(benganrb)
                    .addComponent(duarb)
                    .addComponent(mrurb))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        BUYBTN.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        BUYBTN.setText("BUY ");
        BUYBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUYBTNActionPerformed(evt);
            }
        });

        CLEARBTN.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        CLEARBTN.setText("CLEAR");
        CLEARBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CLEARBTNActionPerformed(evt);
            }
        });

        CANCELBTN.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        CANCELBTN.setText("CANCEL");
        CANCELBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CANCELBTNActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("INSERT MONEY HERE :");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("COLLECT CHANGE :");

        MONEYTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MONEYTFActionPerformed(evt);
            }
        });

        CHNAGETF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CHNAGETFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(BUYBTN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CLEARBTN)
                .addGap(129, 129, 129)
                .addComponent(CANCELBTN)
                .addGap(31, 31, 31))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(84, 84, 84)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(MONEYTF)
                            .addComponent(CHNAGETF, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE))))
                .addContainerGap(111, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(MONEYTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(CHNAGETF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CLEARBTN)
                    .addComponent(BUYBTN)
                    .addComponent(CANCELBTN))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mulirbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mulirbActionPerformed
if(mulirb.isSelected()){
    gajarrb.setSelected(false);
duarb.setSelected(false);
mrurb.setSelected(false);
benganrb.setSelected(false);
halwarb.setSelected(false);
}       // TODO add your handling code here:
    }//GEN-LAST:event_mulirbActionPerformed

    private void MONEYTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MONEYTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MONEYTFActionPerformed

    private void CHNAGETFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CHNAGETFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CHNAGETFActionPerformed

    private void CANCELBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CANCELBTNActionPerformed
System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_CANCELBTNActionPerformed

    private void CLEARBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CLEARBTNActionPerformed
halwarb.setSelected(false);
gajarrb.setSelected(false);
duarb.setSelected(false);
mrurb.setSelected(false);
benganrb.setSelected(false);
mulirb.setSelected(false);
MONEYTF.setText(" ");
CHNAGETF.setText(" ");

// TODO add your handling code here:
    }//GEN-LAST:event_CLEARBTNActionPerformed

    private void halwarbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_halwarbActionPerformed
if(halwarb.isSelected()){
    gajarrb.setSelected(false);
duarb.setSelected(false);
mrurb.setSelected(false);
benganrb.setSelected(false);
mulirb.setSelected(false);
}// TODO add your handling code here:
    }//GEN-LAST:event_halwarbActionPerformed

    private void gajarrbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gajarrbActionPerformed
if(gajarrb.isSelected()){
    halwarb.setSelected(false);
duarb.setSelected(false);
mrurb.setSelected(false);
benganrb.setSelected(false);
mulirb.setSelected(false);
}        // TODO add your handling code here:
    }//GEN-LAST:event_gajarrbActionPerformed

    private void benganrbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_benganrbActionPerformed
if(benganrb.isSelected()){
    gajarrb.setSelected(false);
duarb.setSelected(false);
mrurb.setSelected(false);
halwarb.setSelected(false);
mulirb.setSelected(false);
}        // TODO add your handling code here:
    }//GEN-LAST:event_benganrbActionPerformed

    private void duarbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_duarbActionPerformed
if(duarb.isSelected()){
    gajarrb.setSelected(false);
halwarb.setSelected(false);
mrurb.setSelected(false);
benganrb.setSelected(false);
mulirb.setSelected(false);
}        // TODO add your handling code here:
    }//GEN-LAST:event_duarbActionPerformed

    private void mrurbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mrurbActionPerformed
if(mrurb.isSelected()){
    gajarrb.setSelected(false);
duarb.setSelected(false);
halwarb.setSelected(false);
benganrb.setSelected(false);
mulirb.setSelected(false);
}        // TODO add your handling code here:
    }//GEN-LAST:event_mrurbActionPerformed

    private void BUYBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUYBTNActionPerformed
double money=0;
money=Double.parseDouble(MONEYTF.getText());
if(halwarb.isSelected()){
    money=money-100;
}
else if(gajarrb.isSelected()){
    money=money-1000;
}
else if(mulirb.isSelected()){
    money=money-300;
}
else if(benganrb.isSelected()){
    money=money-900;
}
else if(duarb.isSelected()){
    money=money-1000;
}
else if(mrurb.isSelected()){
    money=money-1;
}
if(money<0){
    JOptionPane.showMessageDialog(rootPane, "BHAII PAISE LEKE AA FIR SAMAN LEYIO");
}else {
    CHNAGETF.setText(Double.toString(money));
}
    }//GEN-LAST:event_BUYBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BUYBTN;
    private javax.swing.JButton CANCELBTN;
    private javax.swing.JTextField CHNAGETF;
    private javax.swing.JButton CLEARBTN;
    private javax.swing.JTextField MONEYTF;
    private javax.swing.JRadioButton benganrb;
    private javax.swing.JRadioButton duarb;
    private javax.swing.JRadioButton gajarrb;
    private javax.swing.JRadioButton halwarb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton mrurb;
    private javax.swing.JRadioButton mulirb;
    // End of variables declaration//GEN-END:variables
}
